### ISSUE TITLE
Allow connection without password.

### ISSUE THREAD

**Issue by aadrian** [CymaticLabs/InfluxDBStudio#10]
Please allow connection without password to:
 - most default installs of InfluxDB don't contain a first user, nor is that activated.

Thank you.

**Comment by meverett** [comment]
This application is pretty much just a visual wrapper on the InfluxData.Net library and it's possible this was an issue of how InfluxData.Net was handling it. I've updated the project to use the latest version of InfluxData.Net and I wasn't able to reproduce the problem. Could you download [the latest release](https://github.com/CymaticLabs/InfluxDBStudio/releases/) and see if you are still having the issue?

**Comment by tihomir-kit** [comment]
I actually got a request for the library a while back to allow empty passwords and that's why you can't reproduce it any more since I see you've upgraded to the latest version of the lib.
