### ISSUE TITLE
Tab Context Menu!

### ISSUE THREAD

**Issue by aadrian** [CymaticLabs/InfluxDBStudio#11]
Please add a Tab Context Menu with at least the following operations:
 - Close all Tabs
 - Close all Tabs except this

Thank you.

**Comment by meverett** [comment]
This feature has been added to [the latest release](https://github.com/CymaticLabs/InfluxDBStudio/releases/tag/v0.2.0-beta.1). Thanks for the idea.

**Comment by aadrian** [comment]
@meverett Wow, thank you :) !
