### ISSUE TITLE
InfluxDBStudio cannot insert data

### ISSUE THREAD

**Issue by Myth2018** [CymaticLabs/InfluxDBStudio#25]
HI
  Prompt for the following error when I insert data。What causes this problem？
![1](https://user-images.githubusercontent.com/38900246/39804368-6d8af5ec-53a6-11e8-8ff8-e9107da34c88.PNG)

**Comment by Myth2018** [comment]
I solved this problem!

**Comment by LzyGit** [comment]
> I solved this problem!

How did you solved?

**Comment by a1664670118** [comment]
How did you solved?
