### ISSUE TITLE
Installation step for mac

### ISSUE THREAD

**Issue by yogeshVU** [CymaticLabs/InfluxDBStudio#6]
How to compile and install on mac?

**Comment by meverett** [comment]
Currently only Windows is supported. I did try to use Mono to run on macOS but the Mono Windows.Forms implementation did not work correctly and I don't personally have the time or interest to try and debug it further to see if it is possible. There are other issues too like Mono and Windows.Forms doesn't support the OS clipboard which is too bad.

**Comment by yogeshVU** [comment]
Is there a possibility to create an executable in the release? So that one doesn't need to manually compile the source?

**Comment by CymaticLabs** [comment]
Sure, I just hadn't gotten around to it yet. I Just added an initial binary release you can find [here](https://github.com/CymaticLabs/InfluxDBStudio/releases).

**Comment by yogeshVU** [comment]
cool thanks!
