### ISSUE TITLE
Password which includes a `#`

### ISSUE THREAD

**Issue by DJWassink** [CymaticLabs/InfluxDBStudio#7]
Cheers for the nice tools!

If I use a password with a `#` in it I get the following error:
![image](https://user-images.githubusercontent.com/1822404/28571205-16605f2e-7142-11e7-945e-065df26ba113.png)

I guess special characters aren't escaped or something? Probably other chars are affected as well?

**Comment by meverett** [comment]
This application is pretty much just a visual wrapper on the InfluxData.Net library and it's possible this was an issue of how InfluxData.Net was handling it. I've updated the project to use the latest version of InfluxData.Net and I wasn't able to reproduce the problem. Could you download [the latest release](https://github.com/CymaticLabs/InfluxDBStudio/releases/) and see if you are still having the issue?

**Comment by DJWassink** [comment]
Working now, thanks for the update 👍
